### PR TITLE
cgnutools: Optimize clang build step, time, and size for future changes

### PR DESCRIPTION
**Pull request by owl4ce**
**1.** Because clang builds in cgnutools don't use shared libs `LLVM_LINK_LLVM_DYLIB:BOOL`, it would be great to link them dynamically without building static libraries. Yeah, even though the wiki/docs say not recommended, but this is temporary toolchain.

> > **BUILD_SHARED_LIBS:BOOL**
> 
> Flag indicating if each LLVM component (e.g. Support) is built as a shared library (ON) or as a static library (OFF). Its default value is OFF. On Windows, shared libraries may be used when building with MinGW, including mingw-w64, but not when building with the Microsoft toolchain.
> 
> > **Note**
> 
> BUILD_SHARED_LIBS is only recommended for use by LLVM developers. If you want to build LLVM as a shared library, you should use the LLVM_BUILD_LLVM_DYLIB option.
> 
> https://llvm.org/docs/CMake.html

**2.** Because clang builds in cgnutools disable backtrace support `LLVM_ENABLE_BACKTRACES:BOOL`, it would be great to completely remove libexecinfo from cgnutools.

---

I hope you like it, so consider this. Thank you.

### CODE REVIEW

**Comment by dslm4515** [comment]
>Because clang builds in cgnutools disable backtrace support LLVM_ENABLE_BACKTRACES:BOOL, it would be great to completely remove libexecinfo from cgnutools.

YES. It has annoyed me for a LONG time that LLVM expects libexecinfo because when building LLVM after MLFS, it was never required.

>it would be great to link them dynamically without building static libraries.

Would the LLVM/Clang build be smaller? I've disliked how `cross-tools` of MLFS is smaller than `cgnutools`... the GCC portion, not the entire tool chain.

**Review by dslm4515 — APPROVED** [review]
smaller is better for cgnutools!

**Comment by owl4ce** [comment]
Wait don't merge this now

**Comment by dslm4515** [comment]
>Wait don't merge this now

Almost did. lol.
_Waiting for your approval_

**Comment by owl4ce** [comment]
> YES. It has annoyed me for a LONG time that LLVM expects libexecinfo because when building LLVM after MLFS, it was never required.

Sure! I think backtrace is only needed for debugging with LLDB or something.

> Would the LLVM/Clang build be smaller? I've disliked how `cross-tools` of MLFS is smaller than `cgnutools`... the GCC portion, not the entire tool chain.

Yes, you can see the total static library size by clang and llvm (.a) in `/cgnutools/lib/`.

---

I seem to have forgotten something, the previous build was around ~1.4G now it's ~300M.
Hmmm.. static libraries in GCC toolchain. Wait, I'll make commit changes.

**Review by owl4ce — COMMENTED** [review]
I think this is already.

**Comment by owl4ce** [comment]
Is the `6-file` step really necessary in cgnutools? I do not think so.

**Comment by dslm4515** [comment]
> Is the 6-file step really necessary in cgnutools? I do not think so.

When i first developed cross-tools for MLFS, `file` was required when building a certain package. This was back before i decided to post my work on github. So i dont know for sure if it is actually required.

**Pull request merged**
